logging:
  level:
    com.susuhan.travelpick: debug
    org.hibernate.sql: debug

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true